version: '3'
# each containers are services
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: ["npm", "start"] 
    
      