version: '3'
# each containers are services
services:
  node-app:
    build:
        context: .
        args:
          - NODE_ENV=development
    volumes:
      # Here '.' ie, current working directory on the host machine will be mounted to '/app' inside the container(sync them). 
      # Any changes made to files in '.' will be immediately reflected inside the container at /app, and vice versa.
      # It is also called bind mound.
      - .:/app
      # The line - /app/node_modules creates a anonymous for the /app/node_modules directory inside the container,
      #  ensuring it persists independently of changes on the host machine.
      # Also called anonymous volume
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=abin     
      - MONGO_PASSWORD=password  
      - SESSION_SECRET=itsverysecret  
    command: ["npm", "run", "dev"]
    
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abin
      - MONGO_INITDB_ROOT_PASSWORD=password     
         